#
# Detekt Configuration
# --------------------
# See: https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
#

complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false
  NestedBlockDepth:
    active: true
    threshold: 4
