name: "Module: Publish"

on:
  ## Manual dispatch
  workflow_dispatch: {}

  ## Sub-workflow call
  workflow_call:
    inputs:
      runner:
        type: string
        required: false
        description: "Runner to use"
      snapshot:
        type: boolean
        default: false
        description: "Snapshot"
      live:
        type: boolean
        default: false
        description: "Live"
    secrets:
      BUILDLESS_APIKEY:
        required: true
        description: "API key for build caching"
      PUBLISH_TOKEN:
        required: true
        description: "Publishing token"
      GPG_PRIVATE_KEY:
        required: true
        description: "GPG private key"

env:
  CI: true

# Read-only permissions by default.
permissions:
  contents: read

# One active build per reference, per workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ## Stage: Download Artifacts
  download-artifacts:
    name: "Setup: Artifacts"
    runs-on: ${{ vars.RUNNER || inputs.runner || 'ubuntu-latest' }}
    permissions:
      contents: read
    outputs:
      artifacts: ${{ steps.download.outputs.artifacts }}
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: "Setup: JDK ${{ inputs.java_version || vars.JVM_VERSION }}"
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: ${{ inputs.java_version || vars.JVM_VERSION }}
          distribution: ${{ inputs.jvm || vars.JVM_VARIANT || 'zulu' }}
      - name: "Setup: Artifacts"
        uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
        with:
          name: libraries-jvm

  ## Stage: Publish Snapshot
  publish-snapshot:
    name: "Publish: Snapshot"
    runs-on: ${{ vars.RUNNER || inputs.runner || 'ubuntu-latest' }}
    needs: ['download-artifacts']
    if: inputs.snapshot
    environment:
      name: "snapshots"
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.azul.com:443
            cdn.azul.com:443
            fulcio.sigstore.dev:443
            github.com:443
            gradle.less.build:443
            gradle.pkg.st:443
            dl.less.build:443
            agent.less.build:443
            global.less.build:443
            maven.pkg.st:443
            gradle.pkg.st:443
            edge.pkg.st:443
            maven.pkg.github.com:443
            rekor.sigstore.dev:443
            scans-in.gradle.com:443
            tuf-repo-cdn.sigstore.dev:443
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: "Setup: Signing Keys"
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: "Setup: JDK ${{ inputs.java_version || vars.JVM_VERSION }}"
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: ${{ inputs.java_version || vars.JVM_VERSION }}
          distribution: ${{ inputs.jvm || vars.JVM_VARIANT || 'zulu' }}
      - name: "Setup: Artifacts"
        uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
        with:
          name: libraries-jvm
      - name: "Publish: Snapshots"
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2
        id: publish
        env:
          CI: true
          BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cache-read-only: false
          arguments: |
            publishSandbox
            -Pstamp=false
            -Pversion=1.0-SNAPSHOT
            --scan
            --warning-mode=none
            --dependency-verification=lenient
            --no-configuration-cache
            -Pci=true

  ## Stage: Publish Live
  publish-live:
    name: "Publish: Live"
    runs-on: ${{ vars.RUNNER || inputs.runner || 'ubuntu-latest' }}
    needs: ['download-artifacts', 'publish-snapshot']
    if: inputs.live
    environment:
      name: "live"
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: "Setup: Signing Keys"
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: "Setup: JDK ${{ inputs.java_version || vars.JVM_VERSION }}"
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: ${{ inputs.java_version || vars.JVM_VERSION }}
          distribution: ${{ inputs.jvm || vars.JVM_VARIANT || 'zulu' }}
      - name: "Setup: Artifacts"
        uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
        with:
          name: libraries-jvm
      - name: "Publish: Live"
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2
        id: publish
        env:
          CI: true
          BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          GITHUB_ACTOR: ${{ vars.PUBLISH_ACTOR }}
        with:
          cache-read-only: false
          arguments: |
            publishAllPublicationsToGitHubPackagesRepository
            -Pstamp=true
            --scan
            --warning-mode=none
            --dependency-verification=lenient
            --no-configuration-cache
            -Pci=true
