name: "Module: Build"

on:
  ## Manual dispatch
  workflow_dispatch: {}

  ## Sub-workflow call
  workflow_call:
    inputs:
      runner:
        type: string
        required: false
        description: "Runner tag to use"
      graph:
        type: string
        required: false
        default: 'disabled'
        description: "Dependency graph mode"
      provenance:
        type: boolean
        required: false
        description: "Generate provenance"
      signing:
        type: boolean
        required: false
        description: "Sign artifacts"
      jvm:
        type: string
        required: false
        description: "JVM variant to build on"
      java_version:
        type: string
        required: false
        description: "Java version to build with"
    secrets:
      SONAR_TOKEN:
        required: true
        description: "SonarCloud token"
      CODECOV_TOKEN:
        required: true
        description: "Coverage reporting token"
      BUILDLESS_APIKEY:
        required: true
        description: "API key for build caching"

env:
  CI: true
  BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}

# Read-only permissions by default.
permissions:
  actions: read
  contents: read

# One active build per reference, per workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ## Stage: Build Library with Gradle
  build:
    name: "Build Library"
    runs-on: ${{ vars.RUNNER || inputs.runner || 'ubuntu-latest' }}
    permissions:
      contents: write
      id-token: write
      checks: write
      pull-requests: read
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: "Setup: JDK ${{ inputs.java_version || vars.JVM_VERSION }}"
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: ${{ inputs.java_version || vars.JVM_VERSION }}
          distribution: ${{ inputs.jvm || vars.JVM_VARIANT || 'zulu' }}
      - name: "Setup: Cache SonarCloud Packages"
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: "Setup: Cache Gradle Packages"
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: "Build: Gradle"
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2
        id: gradlebuild
        env:
          CI: true
          BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          cache-read-only: false
          dependency-graph: ${{ inputs.graph }}
          arguments: |
            build
            test
            check
            preMerge
            --scan
            --warning-mode=none
            --dependency-verification=lenient
            -Pci=true
      - name: "Report: Provenance"
        id: hash
        run: |
          echo "hashes=$(sha256sum ./subprojects/*/build/libs/* | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: "Report: Tests"
        uses: dorny/test-reporter@1e3a380fe6f25600635b111ddb3547864782656a # v1
        if: success() || failure()
        with:
          name: Library Tests
          path: ./subprojects/*/build/test-results/test/TEST-*.xml
          reporter: java-junit
          max-annotations: "0"
          fail-on-error: false
      - name: "Artifact: Libraries"
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        continue-on-error: true
        with:
          name: libraries-jvm
          path: |
            ./subprojects/*/build/libs/*.jar
      - name: "Artifact: Reports"
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        continue-on-error: true
        with:
          name: test-reports-jvm
          path: |
            ./build/reports/kover/merged/xml/report.xml
            ./subprojects/*/build/test-results/test/TEST-*.xml

  ## Stage: Report Coverage
  coverage:
    name: "Tests & Coverage"
    needs: ['build']
    runs-on: ${{ vars.RUNNER || inputs.runner || 'ubuntu-latest' }}
    permissions:
      actions: read
      checks: write
      id-token: write
    steps:
      - name: "Setup: Artifacts"
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: test-reports-jvm
      - name: "Report: Codecov"
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/kover/merged/xml/report.xml

  ## Stage: Build Library with Gradle
  provenance:
    name: "Provenance"
    needs: ['build']
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: ${{ inputs.provenance }}
