name: "Module: Build"

on:
  ## Manual dispatch
  workflow_dispatch: {}

  ## Sub-workflow call
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        description: "Version tag to use"
      runner:
        type: string
        required: false
        description: "Runner tag to use"
      graph:
        type: string
        required: false
        description: "Dependency graph mode"
    secrets:
      SONAR_TOKEN:
        required: true
        description: "SonarCloud token"
      CODECOV_TOKEN:
        required: true
        description: "Coverage reporting token"
      BUILDLESS_APIKEY:
        required: true
        description: "API key for build caching"

env:
  CI: true
  BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}

permissions:
  contents: read

jobs:
  ## Stage: Build Library with Gradle
  build-library:
    name: "Build Library"
    runs-on: ${{ vars.RUNNER || inputs.runner || 'ubuntu-latest' }}
    permissions:
      contents: "read"
      id-token: "write"
      checks: "write"
      pull-requests: "read"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: "Setup: Checkout"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Set up JDK 20
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: 20
          distribution: 'zulu'
      - name: "Setup: Cache SonarCloud Packages"
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: "Setup: Cache Gradle Packages"
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: "Build: Gradle"
        uses: gradle/gradle-build-action@a4cf152f482c7ca97ef56ead29bf08bcd953284c # v2
        id: gradlebuild
        env:
          CI: true
          BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          cache-read-only: false
          dependency-graph: ${{ inputs.graph }}
          arguments: |
            build
            test
            check
            koverXmlReport
            sonar
            --scan
            --warning-mode=none
            --dependency-verification=lenient
            -Pci=true
      - name: "Report: Tests"
        uses: dorny/test-reporter@1e3a380fe6f25600635b111ddb3547864782656a # v1
        if: success() || failure()
        with:
          name: Library Tests
          path: ./subprojects/*/build/test-results/test/TEST-*.xml
          reporter: java-junit
          max-annotations: "0"
          fail-on-error: false
      - name: "Artifact: Reports"
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        continue-on-error: true
        with:
          name: test-reports-jvm
          path: |
            build/reports/kover/merged/xml/report.xml
      - name: "Report: Codecov"
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/kover/merged/xml/report.xml
