name: "Module: Publish"

on:
  ## Manual dispatch
  workflow_dispatch: {}

  ## Sub-workflow call
  workflow_call:
    inputs:
      runner:
        type: string
        required: false
        description: "Runner to use"
      snapshot:
        type: boolean
        default: false
        description: "Snapshot"
      live:
        type: boolean
        default: false
        description: "Live"
    secrets:
      BUILDLESS_APIKEY:
        required: true
        description: "API key for build caching"

env:
  CI: true

# Read-only permissions by default.
permissions:
  contents: read

# One active build per reference, per workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ## Stage: Download Artifacts
  download-artifacts:
    name: "Setup: Artifacts"
    runs-on: ${{ vars.RUNNER || inputs.runner || 'ubuntu-latest' }}
    permissions:
      contents: read
    outputs:
      artifacts: ${{ steps.download.outputs.artifacts }}
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: "Setup: JDK ${{ inputs.java_version || vars.JVM_VERSION }}"
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: ${{ inputs.java_version || vars.JVM_VERSION }}
          distribution: ${{ inputs.jvm || vars.JVM_VARIANT || 'zulu' }}
      - name: "Setup: Artifacts"
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libraries-jvm

  ## Stage: Publish Snapshot
  publish-snapshot:
    name: "Publish: Snapshot"
    runs-on: ${{ vars.RUNNER || inputs.runner || 'ubuntu-latest' }}
    needs: ['download-artifacts']
    if: inputs.snapshot
    environment:
      name: "snapshots"
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: "Setup: Signing Keys"
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: "Setup: JDK ${{ inputs.java_version || vars.JVM_VERSION }}"
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: ${{ inputs.java_version || vars.JVM_VERSION }}
          distribution: ${{ inputs.jvm || vars.JVM_VARIANT || 'zulu' }}
      - name: "Setup: Artifacts"
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libraries-jvm
      - name: "Publish: Snapshots"
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2
        id: publish
        env:
          CI: true
          BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cache-read-only: false
          arguments: |
            publishAllPublicationsToGitHubPackagesRepository
            -Pstamp=false
            -Pversion=1.0-SNAPSHOT
            --scan
            --warning-mode=none
            --dependency-verification=lenient
            --no-configuration-cache
            -Pci=true

  ## Stage: Publish Live
  publish-live:
    name: "Publish: Live"
    runs-on: ${{ vars.RUNNER || inputs.runner || 'ubuntu-latest' }}
    needs: ['download-artifacts', 'publish-snapshot']
    if: inputs.live
    environment:
      name: "live"
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: "Setup: Signing Keys"
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: "Setup: JDK ${{ inputs.java_version || vars.JVM_VERSION }}"
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: ${{ inputs.java_version || vars.JVM_VERSION }}
          distribution: ${{ inputs.jvm || vars.JVM_VARIANT || 'zulu' }}
      - name: "Setup: Artifacts"
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: libraries-jvm
      - name: "Publish: Live"
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2
        id: publish
        env:
          CI: true
          BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cache-read-only: false
          arguments: |
            publishAllPublicationsToGitHubPackagesRepository
            -Pstamp=true
            --scan
            --warning-mode=none
            --dependency-verification=lenient
            --no-configuration-cache
            -Pci=true
