name: "CI"

on:
  ## Event: PR
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  ## Build Library
  build-library:
    name: "Build"
    uses: ./.github/workflows/module.build.yml
    secrets: inherit
    permissions:
      actions: read
      contents: write
      id-token: write
      checks: write
      pull-requests: read
    with:
      graph: generate-and-submit
      signing: true
      provenance: true

  ## Checks: CodeQL
  checks-codeql:
    name: "Checks"
    uses: ./.github/workflows/module.codeql.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
      security-events: write
    with: {}

  ## Checks CodeQL
  checks-detekt:
    name: "Checks"
    uses: ./.github/workflows/module.detekt.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
      security-events: write
    with: {}

  ## Stage: Check Scorecard
  checks-scorecard:
    name: "Checks"
    uses: ./.github/workflows/module.scorecards.yml
    secrets: inherit
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    with: {}

  ## Deploy: Snapshots
  publish:
    name: "Publish"
    uses: ./.github/workflows/module.publish.yml
    secrets: inherit
    needs: ['build-library', 'checks-codeql', 'checks-detekt', 'checks-scorecard']
    permissions:
      contents: read
      packages: write
    with:
      snapshot: true
      live: true
