name: "CI"

on:
  ## Event: PR
  push:
    paths:
      ## Trigger: Global changes/release
      - ".version"
      - ".release"
      - "gradle.properties"
      - "*.kts"
      - "**/*.kts"
      - "**/*.kt"
      - "**/*.java"
      - "**/*.properties"
      - "gradle/**"

permissions:
  contents: read

jobs:
  ## Build Library
  build-library:
    name: "CI: Build"
    uses: ./.github/workflows/module.build.yml
    secrets: inherit
    permissions:
      contents: "read"
    with:
      graph: generate-and-submit
